services:
  caddy:
    image: caddy:alpine
    ports:
      - "8111:80"
    # volumes:
    # - ./Caddyfile:/etc/caddy/Caddyfile
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    depends_on:
      - flask

  flask:
    build:
      context: ./app
      args:
        GIT_COMMIT: ${GIT_COMMIT:-unknown}
        IMAGE_NAME: ${IMAGE_NAME:-cooluptest/flask}
        BUILD_DATE: ${BUILD_DATE:-unknown}
    restart: unless-stopped
    expose:
      - "5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

configs:
  caddyfile:
    content: |
      :80 {
        reverse_proxy flask:5000
      }
